In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../dataset/train.csv")
df.tail()

/tmp/ipykernel_17501/1674214804.py:1: DtypeWarning: Columns (0: PRN, 1: Carrier_Doppler_hz, 2: Pseudorange_m, 3: RX_time, 4: TOW, 5: Carrier_phase, 6: EC, 7: LC, 8: PC, 9: PIP, 10: PQP, 11: TCD, 12: CN0) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("../dataset/train.csv")

,time,channel,PRN,Carrier_Doppler_hz,Pseudorange_m,RX_time,TOW,Carrier_phase,EC,LC,PC,PIP,PQP,TCD,CN0,spoofed
891211,111401,ch3,26,-2113.491414,5482363.057687,263154.8,263154.781713,193060.42721,101265.445312,96612.585938,104833.25,-104328.625,-10273.680664,-2108.602539,42.208794,0
891212,111401,ch4,4,-493.836685,2666524.741959,263154.8,263154.791105,48193.433748,112036.953125,122600.25,124538.890625,124537.945312,-485.292389,-495.879303,43.671265,0
891213,111401,ch5,0,0.0,0.0,263154.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
891214,111401,ch6,0,0.0,0.0,263154.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
891215,111401,ch7,0,0.0,0.0,263154.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [3]:
df.PRN.value_counts()

PRN
0      539935
26      41309
16      36512
4       32951
9       29398
27      28949
0       25719
3       23298
8       22630
7       18225
11      14246
6       14042
12      13071
2       12049
25       9761
19       8762
17       7366
31       5738
12       2015
19       2015
2        1548
6        1463
20        205
ch0         1
ch1         1
ch2         1
ch3         1
ch4         1
ch5         1
ch6         1
ch7         1
24          1
Name: count, dtype: int64

In [4]:
df_test=pd.read_csv("../dataset/test.csv")
df_test.head()

,time,channel,PRN,Carrier_Doppler_hz,Pseudorange_m,RX_time,TOW,Carrier_phase,EC,LC,PC,PIP,PQP,TCD,CN0
0,111402,ch0,8,4749.068417,4.841489e+06,263154.82,263154.803851,-435396.111594,101998.429688,100788.812500,111415.289062,-107731.039062,-28414.615234,4660.467773,43.559540
1,111402,ch1,9,1995.777378,2.449848e+06,263154.82,263154.811828,-201479.950180,100812.039062,98424.367188,109174.476562,-105347.234375,-28653.570312,1997.164185,47.116425
2,111402,ch2,27,3458.024120,3.738822e+06,263154.82,263154.807529,-356000.635312,138335.140625,125640.570312,138446.281250,137254.781250,-18124.476562,3467.803955,45.687332
3,111402,ch3,26,-2105.992470,5.482371e+06,263154.82,263154.801713,193102.504674,84470.195312,84153.156250,95917.468750,95899.140625,1874.903442,-2109.972656,42.264256
4,111402,ch4,4,-493.638193,2.666526e+06,263154.82,263154.811105,48203.346004,103226.210938,100365.203125,114574.656250,-114160.539062,-9732.571289,-494.215881,43.629795

In [5]:
df_test.PRN.value_counts()

PRN
0     194130
4      30033
7      27873
9      26999
27     26779
16     20756
8      19727
30     14054
26     12427
20      9174
Name: count, dtype: int64

In [6]:
df.shape

(891216, 16)

In [7]:
df_test.shape

(381952, 15)

In [8]:
df["channel"].value_counts()

channel
ch0    111402
ch1    111402
ch2    111402
ch3    111402
ch4    111402
ch5    111402
ch6    111402
ch7    111402
Name: count, dtype: int64

In [9]:
cols=[]
for col in df.columns:
    if df[col].dtype == "object":
        print(col)
        cols.append(col)

PRN
Carrier_Doppler_hz
Pseudorange_m
RX_time
TOW
Carrier_phase
EC
LC
PC
PIP
PQP
TCD
CN0

In [10]:
import numpy as np

In [11]:
df.head(10)

,time,channel,PRN,Carrier_Doppler_hz,Pseudorange_m,RX_time,TOW,Carrier_phase,EC,LC,PC,PIP,PQP,TCD,CN0,spoofed
0,0,ch0,ch0,ch0,ch0,ch0,ch0,ch0,ch0,ch0,ch0,ch0,ch0,ch0,ch0,0
1,0,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,0
2,0,ch2,ch2,ch2,ch2,ch2,ch2,ch2,ch2,ch2,ch2,ch2,ch2,ch2,ch2,0
3,0,ch3,ch3,ch3,ch3,ch3,ch3,ch3,ch3,ch3,ch3,ch3,ch3,ch3,ch3,0
4,0,ch4,ch4,ch4,ch4,ch4,ch4,ch4,ch4,ch4,ch4,ch4,ch4,ch4,ch4,0
5,0,ch5,ch5,ch5,ch5,ch5,ch5,ch5,ch5,ch5,ch5,ch5,ch5,ch5,ch5,0
6,0,ch6,ch6,ch6,ch6,ch6,ch6,ch6,ch6,ch6,ch6,ch6,ch6,ch6,ch6,0
7,0,ch7,ch7,ch7,ch7,ch7,ch7,ch7,ch7,ch7,ch7,ch7,ch7,ch7,ch7,0
8,1,ch0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,1,ch1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [12]:
df[df["channel"]=="ch1"]

,time,channel,PRN,Carrier_Doppler_hz,Pseudorange_m,RX_time,TOW,Carrier_phase,EC,LC,PC,PIP,PQP,TCD,CN0,spoofed
1,0,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,0
9,1,ch1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17,2,ch1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
25,3,ch1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
33,4,ch1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
891177,111397,ch1,9,1999.251973,2449884.897812,263154.72,263154.711828,-201280.293824,138201.546875,130189.703125,148845.28125,-148533.546875,-9628.336914,1993.014771,46.903152,0
891185,111398,ch1,9,1997.303206,2449877.634055,263154.74,263154.731828,-201320.22642,125515.179688,148646.515625,151428.828125,151420.125,1623.369629,1991.841431,46.9548,0
891193,111399,ch1,9,1997.908819,2449870.477511,263154.76,263154.751828,-201360.163869,142255.28125,153979.34375,159852.90625,159826.59375,-2900.598633,1991.36499,46.969013,0
891201,111400,ch1,9,1994.144395,2449862.945718,263154.78,263154.771828,-201400.091277,125955.601562,142436.125,148908.265625,146136.5625,28596.816406,1995.646729,47.003902,0
891209,111401,ch1,9,1992.720118,2449855.324579,263154.8,263154.791828,-201440.014629,134102.1875,123972.257812,147107.890625,147106.34375,-675.005127,1991.681152,47.128937,0

In [13]:
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')

In [14]:
df.isna().sum()

time                  0
channel               0
PRN                   8
Carrier_Doppler_hz    8
Pseudorange_m         8
RX_time               8
TOW                   8
Carrier_phase         8
EC                    8
LC                    8
PC                    8
PIP                   8
PQP                   8
TCD                   8
CN0                   8
spoofed               0
dtype: int64

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891216 entries, 0 to 891215
Data columns (total 16 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   time                891216 non-null  int64
 1   channel             891216 non-null  str
 2   PRN                 891208 non-null  float64
 3   Carrier_Doppler_hz  891208 non-null  float64
 4   Pseudorange_m       891208 non-null  float64
 5   RX_time             891208 non-null  float64
 6   TOW                 891208 non-null  float64
 7   Carrier_phase       891208 non-null  float64
 8   EC                  891208 non-null  float64
 9   LC                  891208 non-null  float64
 10  PC                  891208 non-null  float64
 11  PIP                 891208 non-null  float64
 12  PQP                 891208 non-null  float64
 13  TCD                 891208 non-null  float64
 14  CN0                 891208 non-null  float64
 15  spoofed             891216 non-null  int64
dtypes: float64(13), int64(2), str(1)
memory usage: 108.8 MB

In [16]:
df=df.fillna(0)
df.head()

,time,channel,PRN,Carrier_Doppler_hz,Pseudorange_m,RX_time,TOW,Carrier_phase,EC,LC,PC,PIP,PQP,TCD,CN0,spoofed
0,0,ch0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,0,ch1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,0,ch2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,0,ch3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,0,ch4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [17]:
df.shape

(891216, 16)

In [18]:
val_0,val_1 = df.spoofed.value_counts()

In [19]:
val_0/val_1

5.999371701432521

In [20]:
channels=[]
for ch in df.channel.unique():
    channels.append(ch)

In [21]:
df.describe()

,time,PRN,Carrier_Doppler_hz,Pseudorange_m,RX_time,TOW,Carrier_phase,EC,LC,PC,PIP,PQP,TCD,CN0,spoofed
count,891216.000000,891216.000000,891216.000000,8.912160e+05,891216.000000,891216.000000,8.912160e+05,891216.000000,891216.000000,891216.000000,891216.000000,891216.000000,891216.000000,891216.000000,891216.00000
mean,55700.500000,4.969298,481.430745,3.895512e+06,204670.916868,107001.473227,-4.299921e+04,38511.995226,38524.526312,42683.502334,110.903751,12.486616,481.875671,16.289806,0.14287
std,32159.005385,8.477712,1583.515846,8.747258e+06,167156.096505,162325.540259,1.541469e+05,54270.768323,54255.999863,59972.633131,71999.295972,15319.564763,1570.685465,21.545775,0.34994
min,0.000000,0.000000,-4262.754835,-6.892811e+06,0.000000,0.000000,-1.030828e+06,0.000000,0.000000,0.000000,-238664.328125,-210459.406250,-3214.671400,0.000000,0.00000
25%,27850.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
50%,55700.500000,0.000000,0.000000,0.000000e+00,174793.030000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
75%,83551.000000,7.000000,0.000000,2.599326e+06,263002.040000,174895.837258,0.000000e+00,89623.228516,89706.814453,99761.685781,0.000000,0.000000,0.000000,43.535636,0.00000
max,111401.000000,31.000000,9518.651681,2.830762e+07,492039.420000,492039.341092,3.527992e+05,244872.734375,243145.937500,246685.468750,242361.078125,226761.110000,6753.074219,50.148064,1.00000

In [22]:
df_test.describe()

,time,PRN,Carrier_Doppler_hz,Pseudorange_m,RX_time,TOW,Carrier_phase,EC,LC,PC,PIP,PQP,TCD,CN0
count,381952.000000,381952.000000,381952.000000,3.819520e+05,381952.000000,381952.000000,3.819520e+05,381952.000000,381952.000000,381952.000000,381952.000000,381952.000000,381952.000000,381952.000000
mean,135273.500000,7.067330,858.034945,1.808115e+06,187069.660191,129625.207520,-8.174679e+04,53236.344587,53224.766115,58991.162326,-17.659814,-3.181736,860.580448,22.082173
std,13782.523665,9.677686,1803.392877,2.098206e+06,119679.962057,131784.248457,1.883990e+05,58027.524599,57969.271004,64048.034748,85887.775047,14332.022690,1803.344803,22.524074
min,111402.000000,0.000000,-2859.032425,0.000000e+00,0.000000,0.000000,-1.032332e+06,0.000000,0.000000,0.000000,-270777.625000,-192470.062500,-2333.721680,0.000000
25%,123337.750000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,-1.470773e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,135273.500000,0.000000,0.000000,0.000000e+00,263449.150000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,147209.250000,9.000000,2139.469612,3.334400e+06,263753.305000,263633.111592,0.000000e+00,109760.539062,109717.214844,121862.380859,0.000000,0.000000,2138.988953,45.478316
max,159145.000000,30.000000,5006.664021,6.858907e+06,264109.680000,264109.675669,2.609114e+05,239576.562500,244650.390625,271466.125000,235842.562500,200493.656250,4859.546875,49.958927

In [19]:
for ch in channels:
    temp=df[df["channel"]==ch]
    temp.to_csv(f"../dataset/train/train_{ch}.csv",index=False)

In [20]:
for ch in channels:
    temp=df_test[df_test["channel"]==ch]
    temp.to_csv(f"../dataset/test/test_{ch}.csv",index=False)

In [23]:
df.time.value_counts()

time
0         8
1         8
2         8
3         8
4         8
         ..
111397    8
111398    8
111399    8
111400    8
111401    8
Name: count, Length: 111402, dtype: int64

In [36]:
df.PRN.value_counts()

PRN
0.0     565654
26.0     41309
16.0     36512
4.0      32951
9.0      29398
27.0     28949
3.0      23298
8.0      22630
7.0      18225
6.0      15505
12.0     15086
11.0     14246
2.0      13597
19.0     10777
25.0      9761
17.0      7366
31.0      5738
20.0       205
24.0         1
Name: count, dtype: int64

In [55]:
df.groupby(by="channel").spoofed.value_counts()

channel  spoofed
ch0      0          95485
         1          15916
ch1      0          95485
         1          15916
ch2      0          95485
         1          15916
ch3      0          95485
         1          15916
ch4      0          95485
         1          15916
ch5      0          95485
         1          15916
ch6      0          95485
         1          15916
ch7      0          95485
         1          15916
Name: count, dtype: int64

In [25]:
temp=df[df["channel"]=="ch1"]

In [26]:
df.columns

Index(['time', 'channel', 'PRN', 'Carrier_Doppler_hz', 'Pseudorange_m',
       'RX_time', 'TOW', 'Carrier_phase', 'EC', 'LC', 'PC', 'PIP', 'PQP',
       'TCD', 'CN0', 'spoofed'],
      dtype='str')

In [27]:
temp=temp[(temp["Carrier_Doppler_hz"]==0)&(temp["Pseudorange_m"]==0)&(temp["TOW"]==0)&(temp["Carrier_phase"]==0)&(temp["EC"]==0)&(temp["LC"]==0)&(temp["PC"]==0)&(temp["PIP"]==0)&(temp["PQP"]==0)&(temp["TCD"]==0)&(temp["CN0"]==0)]

In [28]:
temp.shape

(70392, 16)

In [29]:
temp.spoofed.value_counts()

spoofed
0    57703
1    12689
Name: count, dtype: int64

In [44]:
df1=df[df["channel"]=="ch1"]

In [45]:
df1.shape

(111402, 16)

In [35]:
temp["continuity_time"]=temp.time.shift(1)-temp.time

In [37]:
temp=temp.fillna(-1)

In [38]:
temp.continuity_time.value_counts()

continuity_time
-1.0       70374
-1549.0        1
-2400.0        1
-5579.0        1
-2955.0        1
-526.0         1
-900.0         1
-1795.0        1
-1077.0        1
-928.0         1
-1498.0        1
-2368.0        1
-603.0         1
-1899.0        1
-621.0         1
-1209.0        1
-2760.0        1
-1919.0        1
-6501.0        1
Name: count, dtype: int64

In [54]:
df1=df1[~df1.time.isin(temp.time)]

In [55]:
df1.shape

(41028, 17)

In [59]:
df1["continuity_time"]=df1.time.shift(1)-df1.time
df1=df1.sort_values(by="time")

In [60]:
df1.continuity_time.value_counts()

continuity_time
-1.0        41009
-9.0            3
-11052.0        1
-3740.0         1
-4546.0         1
-3374.0         1
-1500.0         1
-1923.0         1
-1172.0         1
-9519.0         1
-3632.0         1
-7992.0         1
-4179.0         1
-8833.0         1
-2940.0         1
-2582.0         1
-1300.0         1
Name: count, dtype: int64

In [61]:
df1.spoofed.value_counts()

spoofed
0    37799
1     3229
Name: count, dtype: int64

In [62]:
df1=df1[df1.continuity_time==-1]

In [63]:
df1.head()

,time,channel,PRN,Carrier_Doppler_hz,Pseudorange_m,RX_time,TOW,Carrier_phase,EC,LC,PC,PIP,PQP,TCD,CN0,spoofed,continuity_time
16657,2082,ch1,2.0,2877.576237,955351.766797,491586.04,491586.036813,-84518.809766,147057.02,139984.08,162370.72,162350.50,2561.9800,2875.9893,48.722466,0,-1.0
16665,2083,ch1,2.0,2875.712912,955341.259811,491586.06,491586.056813,-84576.334796,131091.78,133795.88,152239.00,-149054.53,-30975.1250,2879.8108,48.705746,0,-1.0
16673,2084,ch1,2.0,2873.839901,955330.306100,491586.08,491586.076813,-84633.855008,187556.72,175414.20,210121.08,-209548.89,-15496.1600,2877.2366,48.685181,0,-1.0
16681,2085,ch1,2.0,2876.524980,955319.388127,491586.10,491586.096813,-84691.378173,172246.78,159043.45,184453.13,184341.69,6410.6387,2876.3696,48.667812,0,-1.0
16689,2086,ch1,2.0,2874.668957,955308.416547,491586.12,491586.116813,-84748.894468,144233.19,143206.03,158975.58,-158103.84,-16625.5800,2877.8049,48.634621,0,-1.0